export interface IFinancijskaTransakcija {
    t_ID: number,
    predmeT_ID: number,
    izvoD_ID: number,
    t_DIR: string,
    a_RN: string,
    a_FIS: string,
    a_FIN: string,
    a_FID: string,
    a_NA: string,
    a_ID: string,
    t_DV: Date | string,
    t_REF: string,
    t_VR: string,
    t_IZ: string,
    t_VL: string,
    t_KONV_IZ: string,
    t_DESC: string,
    b_RN: string,
    b_FIS: string,
    b_FIN: string,
    b_FID: string,
    b_NA: string,
    b_ID: string
}